-- AlterTable
ALTER TABLE "SystemSettings" ADD COLUMN     "allowedRadiusMeters" DOUBLE PRECISION NOT NULL DEFAULT 200.0,
ADD COLUMN     "officeLatitude" DOUBLE PRECISION NOT NULL DEFAULT 12.971598,
ADD COLUMN     "officeLongitude" DOUBLE PRECISION NOT NULL DEFAULT 77.594562;
